pages:
 # key is the dirname of pages in src/pages
 home:
  # 首页配置
  zh-cn:
   title: 'OpenQueue - 为中小型Web应用提供高并发场景下的流量控制解决方案和服务'
   keywords: '中小型Web应用,高并发限流,流量限制,排队系统'
   description: 'OpenQueue提供基于OAuth2的第三方Web应用流量控制服务。通过限制同时访问用户数，让你的网站系统从容应对高并发访问。'
  # home config
  en-us:
   title: 'OpenQueue - An access rate control system for any web applications.'
   keywords: 'access rate control,queuing system,web applications'
   description: 'An access rate control system for any web applications.'
 community:
  # 社区页配置
  zh-cn:
   title: '社区 - OpenQueue'
   keywords: '关键词1，关键词2'
   description: '页面内容简介'
  # community page config
  en-us:
   title: 'Community - OpenQueue'
   keywords: 'keyword1,keyword2'
   description: 'page description'
 blog:
  # 博客列表页配置
  zh-cn:
   title: '博客 - OpenQueue'
   keywords: '关键词1，关键词2'
   description: '页面内容简介'
  en-us:
   # blog list page config
   title: 'Blog - OpenQueue'
   keywords: 'keyword1,keyword2'
   description: 'page description'