pages:
 # key is the dirname of pages in src/pages
 home:
  # 首页配置
  zh-cn:
   title: 'OpenQueue - 一个基于队列的通用型Web应用访问控制系统'
   keywords: '高并发限流,排队系统'
   description: '一个基于队列的通用型Web应用访问控制系统'
  # home config
  en-us:
   title: 'OpenQueue - A queue-based access control system for any web applications.'
   keywords: 'access control,queuing system'
   description: 'A queue-based access control system for any web applications.'
 community:
  # 社区页配置
  zh-cn:
   title: '社区 - OpenQueue'
   keywords: '关键词1，关键词2'
   description: '页面内容简介'
  # community page config
  en-us:
   title: 'Community - OpenQueue'
   keywords: 'keyword1,keyword2'
   description: 'page description'
 blog:
  # 博客列表页配置
  zh-cn:
   title: '博客 - OpenQueue'
   keywords: '关键词1，关键词2'
   description: '页面内容简介'
  en-us:
   # blog list page config
   title: 'Blog - OpenQueue'
   keywords: 'keyword1,keyword2'
   description: 'page description'