pages:
 # key is the dirname of pages in src/pages
 home:
  # 首页配置
  zh-cn:
   title: 'OpenQueue - 提供通用型Web应用高并发限流解决方案'
   keywords: '海量高并发,排队系统,限流,云服务'
   description: '提供面向Web应用的高并发大容量队列限流云服务，通过简易的Web服务接入方式，限制同时访问人数，让你的网站系统从容应对高并发访问。'
  # home config
  en-us:
   title: 'OpenQueue - A general queuing system'
   keywords: 'cloud,queuing system'
   description: 'A cloud-based queuing system which enables C1000K capability for any web applications.'
 community:
  # 社区页配置
  zh-cn:
   title: '社区 - OpenQueue'
   keywords: '关键词1，关键词2'
   description: '页面内容简介'
  # community page config
  en-us:
   title: 'Community - OpenQueue'
   keywords: 'keyword1,keyword2'
   description: 'page description'
 blog:
  # 博客列表页配置
  zh-cn:
   title: '博客 - OpenQueue'
   keywords: '关键词1，关键词2'
   description: '页面内容简介'
  en-us:
   # blog list page config
   title: 'Blog - OpenQueue'
   keywords: 'keyword1,keyword2'
   description: 'page description'